In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

path_04 = '/Users/joel/Library/CloudStorage/OneDrive-UniversityofSouthampton/Post Grad/ZTF18abuamgo_CLAGN_Project/2009_Analysis/'
path_22 = '/Users/joel/Library/CloudStorage/OneDrive-UniversityofSouthampton/Post Grad/ZTF18abuamgo_CLAGN_Project/2022_Analysis/'
path_24 = '/Users/joel/Library/CloudStorage/OneDrive-UniversityofSouthampton/Post Grad/ZTF18abuamgo_CLAGN_Project/2024_Analysis/'

fur_results_04 = pd.read_csv(path_04 + 'mcmc_fur_results.csv') # Combined line complex parameters
fur_results_22 = pd.read_csv(path_22 + 'mcmc_fur_results.csv')
fur_results_24 = pd.read_csv(path_24 + 'mcmc_fur_results.csv')

fur_results_22

,Unnamed: 0,line_comp,fwhm,fwhm_err,sigma,sigma_err,ew,ew_err,peak,peak_err,area,area_err,snr,snr_err
0,0,OII,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,NeIII,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,Hep,2820.266418,552.633244,1181.217940,231.735381,7.082033,1.829278,3963.381683,2.307495,246.228460,63.695193,2.017094,0.585817
3,3,Hd,4106.640549,383.485595,1720.580351,160.754730,21.131986,1.937396,4091.614735,2.454741,565.537583,52.173230,4.352947,0.457132
4,4,Hg,4744.367345,292.683014,1987.806598,122.659569,61.145979,3.250747,4339.588515,1.368135,1052.311883,56.075921,6.993879,0.536830
5,5,Hb,5055.909447,231.206606,5710.351177,171.547027,250.282069,9.772460,4856.740188,1.098075,2439.798871,95.076524,27.603459,2.102865
6,6,HeI,13923.883429,1046.677873,5836.509982,439.076773,90.010580,6.516641,5875.329265,1.546215,722.158047,52.261323,2.889712,0.163646
7,7,OI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,8,Ha,4449.927552,71.890732,1864.198487,30.124472,544.021470,11.649782,6558.148912,0.703111,4897.775213,104.744748,56.726117,2.711443

In [3]:
# Get Balmer line fluxes
Hb_04 = fur_results_04.loc[5]['area']
Ha_04 = fur_results_04.loc[8]['area']
Hg_04 = fur_results_04.loc[4]['area']
Hd_04 = fur_results_04.loc[3]['area']

Hb_22 = fur_results_22.loc[5]['area']
Ha_22 = fur_results_22.loc[8]['area']
Hg_22 = fur_results_22.loc[4]['area']
Hd_22 = fur_results_22.loc[3]['area']

In [4]:
# Balmer line flux ratios
Ha_frac_22 = Ha_22/Hb_22
Hg_frac_22 = Hg_22/Hb_22
Hd_frac_22 = Hd_22/Hb_22

print('2022 Hb Flux Ratios:')
print('Ha/Hb: ' + str(Ha_frac_22))
print('Hg/Hb: ' + str(Hg_frac_22))
print('Hd/Hb: ' + str(Hd_frac_22))

Ha_frac_04 = Ha_22/Hb_04
Hg_frac_04 = Hg_22/Hb_04
Hd_frac_04 = Hd_22/Hb_04

print('')
print('2009 Hb Flux Ratios:')
print('Ha/Hb: ' + str(Ha_frac_04))
print('Hg/Hb: ' + str(Hg_frac_04))
print('Hd/Hb: ' + str(Hd_frac_04))

2022 Hb Flux Ratios:
Ha/Hb: 2.007450397038374
Hg/Hb: 0.4313109146442969
Hd/Hb: 0.23179680490609245

2009 Hb Flux Ratios:
Ha/Hb: 3.656402071023375
Hg/Hb: 0.7855965576469717
Hd/Hb: 0.4221983859554544

In [27]:
Ha_frac_22

2.007450397038374